export const APPWRITE_CONFIG = {
  endpoint: 'https://sgp.cloud.appwrite.io/v1',
  projectId: '6a79822b003adde92f63',
  apiKey: process.env.APPWRITE_API_KEY || '',
  databaseId:
    process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID ||
    process.env.APPWRITE_DATABASE_ID ||
    'helpa_main',
  buckets: {
    chatMedia: process.env.APPWRITE_BUCKET_CHAT_MEDIA || 'chat-media',
    voiceTranscripts:
      process.env.APPWRITE_BUCKET_VOICE_TRANSCRIPTS || 'voice-transcripts',
    webhookPayloads:
      process.env.APPWRITE_BUCKET_WEBHOOK_PAYLOADS || 'webhook-payloads',
    pdfTickets: process.env.APPWRITE_BUCKET_PDF_TICKETS || 'pdf-tickets',
  },
  collections: {
    accounts: 'accounts',
    profiles: 'profiles',
    memberships: 'memberships',
    contacts: 'contacts',
    patients: 'patients',
    leads: 'leads',
    leadStageHistory: 'lead_stage_history',
    conversations: 'conversations',
    messages: 'messages',
    appointments: 'appointments',
    calls: 'calls',
    voiceIntegrations: 'voice_integrations',
    voiceCommands: 'voice_commands',
    followups: 'followups',
    integrations: 'integrations',
    providerEvents: 'provider_events',
    auditLogs: 'audit_logs',
    calendlyConnections: 'calendly_connections',
    calendlyEventTypes: 'calendly_event_types',
    serviceEventTypeMappings: 'service_event_type_mappings',
    whatsappConfigs: 'whatsapp_configs',
    contactChannels: 'contact_channels',
    idempotencyKeys: 'idempotency_keys',
    outboundOutbox: 'outbound_outbox',
    flowRuns: 'flow_runs',
    messageTemplates: 'message_templates',
    accountInvitations: 'account_invitations',
    automations: 'automations',
    flows: 'flows',
    broadcasts: 'broadcasts',
    plans: 'plans',
    campaigns: 'campaigns',
    doctors: 'doctors',
    departments: 'departments',
    knowledgeBase: 'knowledge_base',
    workerHealth: 'worker_health',
  },
};
