'use client';

import { useEffect, useRef, useState } from 'react';
import { CalendarDays, ImagePlus, MapPin, Plus, Trash2, Users } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Dialog, DialogContent } from '@/components/ui/dialog';
import { toast } from 'sonner';
import { createTourPackageRequest, fetchTourPackage, updateTourPackageRequest } from '@/lib/travel/api-client';
import { uploadAccountMedia } from '@/lib/storage/upload-media';
import { TOUR_PACKAGE_CATEGORIES, TOUR_PACKAGE_CURRENCIES, TOUR_PACKAGE_TYPES, type TourPackageDetail, type TourPackageWriteInput } from '@/lib/travel/types';

type FormState = TourPackageWriteInput & { image_url?: string | null; min_people?: number | null; max_people?: number | null; price_for?: string };
const INCLUDED = ['Hotel Stay', 'Transport (Car/Bus)', 'Food (Meals)', 'Sightseeing', 'Activities', 'Tour Guide', 'Airport Pick-up', 'Entry Tickets', 'Other'];
const EXCLUDED = ['Flight / Train Tickets', 'Personal Expenses', 'Travel Insurance', 'Visa Fees', 'Other'];

function emptyForm(): FormState {
  return { name: '', destination: '', description: '', package_type: 'Family', category: 'Domestic', duration_days: 5, duration_nights: 4, starting_price: 0, currency: 'INR', price_for: 'Per Person', status: 'active', featured: false, valid_from: '', valid_until: '', booking_notes: '', terms_and_conditions: '', image_url: null, min_people: 2, max_people: 20, itineraries: Array.from({ length: 5 }, (_, i) => ({ day_number: i + 1, title: '', description: '', activities: '', meals: '', hotel: '', overnight_location: '' })), inclusions: [], exclusions: [], hotels: [], pricing: [], departures: [] };
}
function fromDetail(pkg: TourPackageDetail & Partial<FormState>): FormState { return { ...emptyForm(), ...pkg, itineraries: pkg.itineraries?.length ? pkg.itineraries : emptyForm().itineraries, inclusions: pkg.inclusions || [], exclusions: pkg.exclusions || [], hotels: pkg.hotels || [], pricing: pkg.pricing || [], departures: pkg.departures || [] }; }

export function TourPackageFormDialog({ open, packageId, onOpenChange, onSaved }: { open: boolean; packageId: string | null; onOpenChange: (open: boolean) => void; onSaved: () => void }) {
  const [form, setForm] = useState<FormState>(emptyForm());
  const [saving, setSaving] = useState(false);
  const [uploading, setUploading] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);
  useEffect(() => { if (!open) return; if (!packageId) { setForm(emptyForm()); return; } fetchTourPackage(packageId).then((pkg) => setForm(fromDetail(pkg as TourPackageDetail & Partial<FormState>))).catch((e) => toast.error((e as Error).message || 'Failed to load package')); }, [open, packageId]);
  const setField = <K extends keyof FormState>(key: K, value: FormState[K]) => setForm((current) => ({ ...current, [key]: value }));
  const updateArray = <K extends 'itineraries' | 'inclusions' | 'exclusions'>(key: K, value: FormState[K]) => setField(key, value);
  const choosePhoto = async (file?: File) => { if (!file) return; if (!file.type.startsWith('image/')) return toast.error('Please choose an image'); if (file.size > 5 * 1024 * 1024) return toast.error('Photo must be 5MB or smaller'); setUploading(true); try { const uploaded = await uploadAccountMedia('tour-package-media', file); setField('image_url', uploaded.publicUrl); } catch (e) { toast.error((e as Error).message || 'Photo upload failed'); } finally { setUploading(false); } };
  const save = async () => { if (!form.name.trim() || !form.destination.trim()) return toast.error('Package name and destination are required'); if (form.min_people && form.max_people && form.max_people < form.min_people) return toast.error('Maximum people cannot be less than minimum people'); setSaving(true); try { const payload = form as TourPackageWriteInput; if (packageId) await updateTourPackageRequest(packageId, payload); else await createTourPackageRequest(payload); toast.success(packageId ? 'Package updated' : 'Package created'); onSaved(); onOpenChange(false); } catch (e) { toast.error((e as Error).message || 'Failed to save package'); } finally { setSaving(false); } };
  const addDay = () => updateArray('itineraries', [...(form.itineraries || []), { day_number: (form.itineraries || []).length + 1, title: '', description: '', activities: '', meals: '', hotel: '', overnight_location: '' }]);
  const toggleItem = (key: 'inclusions' | 'exclusions', item: string) => { const current = (form[key] || []) as Array<{ item: string }>; const exists = current.some((row) => row.item === item); updateArray(key, exists ? current.filter((row) => row.item !== item) : [...current, { item }]); };
  const fieldClass = 'h-10 rounded-lg border-slate-200 bg-white text-sm';
  const cardClass = 'rounded-xl border border-slate-200 bg-white p-5 shadow-sm';

  return <Dialog open={open} onOpenChange={onOpenChange}>
    <DialogContent className="!h-[92vh] !w-[calc(100vw-48px)] !max-w-none sm:!max-w-none max-h-[920px] min-w-0 overflow-hidden rounded-2xl p-0">
      <div className="flex min-h-0 h-full flex-col">
        <div className="flex shrink-0 items-center justify-between border-b bg-white px-7 py-5 pr-16">
          <div><h2 className="text-2xl font-bold tracking-tight text-slate-900">{packageId ? 'Edit Tour Package' : 'Create Tour Package'}</h2><p className="mt-1 text-sm text-slate-500">Fill in the details below to add a new tour package.</p></div>
          <div className="flex items-center gap-3"><Button variant="outline" onClick={() => onOpenChange(false)} className="h-10 rounded-lg px-5">Cancel</Button><Button onClick={() => void save()} disabled={saving || uploading} className="h-10 rounded-lg bg-emerald-500 px-5 font-semibold text-white hover:bg-emerald-600">{saving ? 'Saving...' : 'Save Package'}</Button></div>
        </div>

        <div className="min-h-0 flex-1 overflow-y-auto bg-slate-50/70 px-7 py-6">
          <div className="mx-auto grid max-w-[1180px] grid-cols-1 gap-5 lg:grid-cols-[minmax(0,1.15fr)_minmax(360px,0.85fr)]">
            <section className={cardClass}>
              <h3 className="text-lg font-bold text-slate-900">Basic Details</h3>
              <div className="mt-5 grid grid-cols-2 gap-4">
                <div><Label>Package Name <span className="text-rose-500">*</span></Label><Input className={fieldClass} placeholder="e.g. Darjeeling 4 Nights 5 Days" value={form.name} onChange={(e) => setField('name', e.target.value)} /></div>
                <div><Label>Where is it? <span className="text-rose-500">*</span></Label><div className="relative"><MapPin className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><Input className={`${fieldClass} pl-9`} placeholder="Select place" value={form.destination} onChange={(e) => setField('destination', e.target.value)} /></div></div>
                <div><Label>How many days? <span className="text-rose-500">*</span></Label><select className="mt-1 h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm" value={form.duration_days} onChange={(e) => setField('duration_days', Number(e.target.value))}>{Array.from({ length: 30 }, (_, i) => <option key={i + 1} value={i + 1}>{i + 1} Days</option>)}</select></div>
                <div><Label>How many nights?</Label><select className="mt-1 h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm" value={form.duration_nights} onChange={(e) => setField('duration_nights', Number(e.target.value))}>{Array.from({ length: 30 }, (_, i) => <option key={i} value={i}>{i} Nights</option>)}</select></div>
                <div><Label>Price (₹) <span className="text-rose-500">*</span></Label><Input className={fieldClass} type="number" min="0" placeholder="e.g. 15000" value={form.starting_price ?? ''} onChange={(e) => setField('starting_price', e.target.value === '' ? null : Number(e.target.value))}/></div>
                <div><Label>Price for <span className="text-rose-500">*</span></Label><select className="mt-1 h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm" value={form.price_for || 'Per Person'} onChange={(e) => setField('price_for', e.target.value)}><option>Per Person</option><option>Per Couple</option><option>Per Group</option></select></div>
                <div className="col-span-2"><div className="flex items-center justify-between"><Label>Short details about this package <span className="text-rose-500">*</span></Label><span className="text-xs text-slate-400">Max 200 characters</span></div><textarea maxLength={200} className="mt-2 min-h-[145px] w-full resize-y rounded-lg border border-slate-200 bg-white p-3 text-sm outline-none transition focus:border-emerald-400 focus:ring-2 focus:ring-emerald-100" placeholder="Write a few lines about this package..." value={form.description || ''} onChange={(e) => setField('description', e.target.value)}/><div className="mt-1 text-right text-xs text-slate-400">{(form.description || '').length}/200</div></div>
              </div>
            </section>

            <div className="space-y-5">
              <section className={cardClass}><h3 className="text-lg font-bold text-slate-900">Package Photo</h3><p className="mt-1 text-sm text-slate-500">Add a nice photo of this tour.</p><button type="button" onClick={() => fileRef.current?.click()} className="mt-4 flex h-52 w-full flex-col items-center justify-center overflow-hidden rounded-xl border border-dashed border-slate-300 bg-slate-50 transition hover:bg-slate-100">{form.image_url ? <img src={form.image_url} alt="Package preview" className="h-full w-full object-cover"/> : <><ImagePlus className="h-10 w-10 text-slate-400"/><span className="mt-3 text-sm font-medium text-slate-600">Drag and drop an image here</span><span className="my-1 text-xs text-slate-400">or</span><span className="rounded-lg border bg-white px-5 py-2 text-sm font-semibold shadow-sm">{uploading ? 'Uploading...' : 'Choose Photo'}</span><span className="mt-3 text-xs text-slate-400">Recommended size: 1200×800px · Max 5MB</span></>}</button><input ref={fileRef} type="file" accept="image/*" className="hidden" onChange={(e) => void choosePhoto(e.target.files?.[0])}/></section>
              <section className={cardClass}><h3 className="text-lg font-bold text-slate-900">When can people travel?</h3><div className="mt-4 grid grid-cols-2 gap-4"><div><Label>Available From</Label><Input className={fieldClass} type="date" value={form.valid_from || ''} onChange={(e) => setField('valid_from', e.target.value)}/></div><div><Label>Available Until</Label><Input className={fieldClass} type="date" value={form.valid_until || ''} onChange={(e) => setField('valid_until', e.target.value)}/></div></div></section>
              <section className={cardClass}><h3 className="text-lg font-bold text-slate-900">For how many people?</h3><div className="mt-4 grid grid-cols-2 gap-4"><div><Label>Minimum People</Label><div className="relative"><Users className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><Input className={`${fieldClass} pl-9`} type="number" min="1" value={form.min_people ?? ''} onChange={(e) => setField('min_people', e.target.value === '' ? null : Number(e.target.value))}/></div></div><div><Label>Maximum People</Label><Input className={fieldClass} type="number" min="1" value={form.max_people ?? ''} onChange={(e) => setField('max_people', e.target.value === '' ? null : Number(e.target.value))}/></div></div></section>
            </div>

            <section className={`${cardClass} lg:col-span-2`}><h3 className="text-lg font-bold text-slate-900">What's Included? <span className="text-sm font-normal text-slate-500">(This package has)</span></h3><p className="mt-1 text-sm text-slate-500">Tick all that apply.</p><div className="mt-4 flex flex-wrap gap-2.5">{INCLUDED.map((item) => { const active = form.inclusions?.some((x) => x.item === item); return <button key={item} type="button" onClick={() => toggleItem('inclusions', item)} className={`rounded-lg border px-3.5 py-2 text-sm font-semibold transition ${active ? 'border-emerald-300 bg-emerald-50 text-emerald-700' : 'border-slate-200 bg-white text-slate-600 hover:border-slate-300'}`}>{active ? '✓ ' : ''}{item}</button>; })}</div></section>

            <section className={`${cardClass} lg:col-span-2`}><div className="flex items-center justify-between"><div><h3 className="text-lg font-bold text-slate-900">Plan for Each Day</h3><p className="mt-1 text-sm text-slate-500">Tell us what people will do each day.</p></div><Button type="button" variant="outline" size="sm" onClick={addDay} className="rounded-lg"><Plus className="mr-1.5 h-4 w-4"/> Add Day</Button></div><div className="mt-5 space-y-3">{(form.itineraries || []).map((day, index) => <div key={index} className="grid grid-cols-[72px_minmax(0,1.3fr)_minmax(0,1fr)_minmax(0,1fr)_40px] items-center gap-3 rounded-lg border border-slate-100 bg-slate-50/60 p-2"><span className="rounded-lg bg-white px-2 py-2.5 text-center text-xs font-bold text-slate-600 shadow-sm">Day {index + 1}</span><Input className={fieldClass} placeholder="e.g. Arrival & check-in" value={day.title || ''} onChange={(e) => updateArray('itineraries', form.itineraries!.map((r, i) => i === index ? { ...r, title: e.target.value } : r))}/><Input className={fieldClass} placeholder="Activities" value={day.activities || ''} onChange={(e) => updateArray('itineraries', form.itineraries!.map((r, i) => i === index ? { ...r, activities: e.target.value } : r))}/><Input className={fieldClass} placeholder="Meals / hotel" value={day.meals || ''} onChange={(e) => updateArray('itineraries', form.itineraries!.map((r, i) => i === index ? { ...r, meals: e.target.value } : r))}/><button type="button" disabled={form.itineraries!.length <= 1} onClick={() => updateArray('itineraries', form.itineraries!.filter((_, i) => i !== index).map((r, i) => ({ ...r, day_number: i + 1 })))} className="flex h-10 w-10 items-center justify-center rounded-lg text-rose-500 hover:bg-rose-50 disabled:opacity-30"><Trash2 className="h-4 w-4"/></button></div>)}</div></section>

            <section className={cardClass}><h3 className="text-lg font-bold text-slate-900">What's Not Included?</h3><p className="mt-1 text-sm text-slate-500">Tick all that apply.</p><div className="mt-4 flex flex-wrap gap-2.5">{EXCLUDED.map((item) => { const active = form.exclusions?.some((x) => x.item === item); return <button key={item} type="button" onClick={() => toggleItem('exclusions', item)} className={`rounded-lg border px-3.5 py-2 text-sm font-semibold transition ${active ? 'border-rose-300 bg-rose-50 text-rose-700' : 'border-slate-200 bg-white text-slate-600 hover:border-slate-300'}`}>{active ? '✓ ' : ''}{item}</button>; })}</div></section>
            <section className={cardClass}><h3 className="text-lg font-bold text-slate-900">Category & Tags</h3><p className="mt-1 text-sm text-slate-500">Help people find your package easily.</p><div className="mt-4 grid grid-cols-2 gap-4"><div><Label>Category</Label><select className="mt-1 h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm" value={form.category || ''} onChange={(e) => setField('category', e.target.value)}>{TOUR_PACKAGE_CATEGORIES.map((x) => <option key={x}>{x}</option>)}</select></div><div><Label>Tags <span className="font-normal text-slate-400">(Optional)</span></Label><Input className={fieldClass} placeholder="e.g. Hill Station, Family" value={form.booking_notes || ''} onChange={(e) => setField('booking_notes', e.target.value)}/></div></div></section>

            <section className={`${cardClass} lg:col-span-2`}><div className="grid gap-4 sm:grid-cols-3"><div><Label>Package Type</Label><select className="mt-1 h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm" value={form.package_type || ''} onChange={(e) => setField('package_type', e.target.value)}>{TOUR_PACKAGE_TYPES.map((x) => <option key={x}>{x}</option>)}</select></div><div><Label>Currency</Label><select className="mt-1 h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm" value={form.currency || 'INR'} onChange={(e) => setField('currency', e.target.value)}>{TOUR_PACKAGE_CURRENCIES.map((x) => <option key={x}>{x}</option>)}</select></div><div><Label>Package Status</Label><select className="mt-1 h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm" value={form.status || 'active'} onChange={(e) => setField('status', e.target.value as 'active' | 'inactive')}><option value="active">Active</option><option value="inactive">Inactive</option></select></div></div></section>
          </div>
        </div>
      </div>
    </DialogContent>
  </Dialog>;
}
