import { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/solutions/',
          '/features/',
          '/compare/',
          '/pricing',
          '/security',
          '/contact',
          '/privacy',
          '/terms',
          '/refund',
          '/llms.txt',
          '/llms-full.txt',
        ],
        disallow: [
          '/api/',
          '/admin/',
          '/dashboard/',
          '/inbox/',
          '/appointments/',
          '/broadcasts/',
          '/campaign-reports/',
          '/contacts/',
          '/customers/',
          '/leads/',
          '/lead-forms/',
          '/knowledge-base/',
          '/automations/',
          '/agents/',
          '/billing/',
          '/settings/',
          '/integrations/',
          '/templates/',
          '/tags/',
          '/quick-replies/',
          '/packages/',
          '/members/',
          '/memberships/',
          '/orders/',
          '/invoices/',
          '/doctors/',
          '/departments/',
          '/lab-reports/',
          '/classes/',
          '/courses/',
          '/admissions/',
          '/booking-trip/',
          '/f/',
          '/proposal/',
          '/join/',
          '/auth/',
          '/login',
          '/signup',
          '/forgot-password',
          '/reset-password',
        ],
      },
    ],
    sitemap: 'https://helpa.studio/sitemap.xml',
    host: 'https://helpa.studio',
  };
}
